// <auto-generated />
namespace InternetSpeedLogger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ClarifiedServerPK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClarifiedServerPK));
        
        string IMigrationMetadata.Id
        {
            get { return "201807010406523_ClarifiedServerPK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
